apiVersion: openslo/v1
kind: SLO
metadata:
  name: drift_gen_Calendar
  displayName: DriftGen SLO Calendar
  annotations:
    sumologic/signal-type: Latency
    sumologic/slo-folder-id: 0000000000000ABC
spec:
  description: test slo created from slogen
  service: tsat
  budgetingMethod: Occurrences
  indicator:
    metadata:
      name: driftgen-latency-calendar
      displayName: DriftGen Latency Calendar
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: sumologic-logs
            metricSourceRef: sumologic-datasource
            spec:
              query: |
                  _sourceCategory=tsat-batcher 
                    | where msg="DriftGen query completed" and duration_ms < 400
        total:
          metricSource:
            type: sumologic-logs
            metricSourceRef: sumologic-datasource
            spec:
              query: |
                _sourceCategory=tsat-batcher 
                  | where msg="DriftGen query completed"
  timeWindow:
    - duration: Week
      isRolling: false
      calendar:
        startTime: Monday
        timeZone: America/New_York
  objectives:
    - displayName: Foo Total Errors
      target: 0.98
  alertPolicies:
    - High-Burn-Rate
    - SLA-breach
