apiVersion: openslo/v1alpha
kind: SLO
metadata:
  displayName: Anomaly generation
  name: drift-gen-2
spec:
  service: tsat
  description: checks anomaly are being calculated and with acceptable delays
  budgetingMethod: Timeslices
  objectives:
    - ratioMetrics:
        good:
          source: sumologic
          queryType: Logs
          query: '!isNull(duration) and duration < 1200'
        incremental: true
        total:
          source: sumologic
          queryType: Logs
          query: '_sourceCategory=tsat-batcher | where msg="finished drift genQuery run for active customers"'
      displayName: delay less than 350
      target: 0.98
  timeWindows:
    - count: 1
      isRolling: true
      unit: Day
createView: true
fields:
  aws_region: "Region"
labels:
  tier: 0
burnRateAlerts:
  - shortWindow: '10m'
    shortLimit: 14
    longWindow: '1h'
    longLimit: 14
    notifications:
      - connetionType: 'Email'
        recipients: 'agaurav@sumologic.com'

