apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: High-Burn-Rate
  displayName: Alert Policy
spec:
  description: Alert policy for high burn rate breaches, notifies on-call devops via email & slack
  alertWhenBreaching: true
  alertWhenResolved: false
  conditions:
    - kind: AlertCondition
      metadata:
        name: High-Burn-Rate
        displayName: error budget depleting too fast
      spec:
        description: SLO burn rate exceeds 2 times the acceptable burn rate
        severity: warning
        condition:
          kind: burnrate
          threshold: 2
          lookbackWindow: -1h
          alertAfter: 5m
    - kind: AlertCondition
      metadata:
        name: High-Burn-Rate
        displayName: error budget depleting too fast
      spec:
        description: SLO burn rate exceeds 4 times the acceptable burn rate
        severity: critical
        condition:
          kind: burnrate
          threshold: 4
          lookbackWindow: -1h
          alertAfter: 5m
  notificationTargets:
    - targetRef: OnCallDevopsMailNotification
    - targetRef: OnCallDevopsSlackNotification


