apiVersion: openslo/v1
kind: SLO
metadata:
  name: TestSLO_Rolling
  displayName: Test SLO
  annotations:
    sumologic/signal-type: Latency
spec:
  description: test slo created from slogen
  service: TheServiceName
  indicator:
    metadata:
      name: foo-error
      displayName: Foo Error
    spec:
      ratioMetric:
        counter: true
        good:
          metricSource:
            type: sumologic-logs
            metricSourceRef: sumologic-datasource
            spec:
              query: |
                _sourceCategory=tsat-batcher 
                  | where msg="DriftGen query completed" and duration_ms < 400
        total:
          metricSource:
            type: sumologic-logs
            metricSourceRef: sumologic-datasource
            spec:
              query: |
                _sourceCategory=tsat-batcher 
                  | where msg="DriftGen query completed"
  timeWindow:
    - duration: 1M
      isRolling: true
  budgetingMethod: Occurrences
  objectives:
    - displayName: Foo Total Errors
      target: 0.98
