apiVersion: openslo/v1alpha
kind: SLO
metadata:
  displayName: Checkout action delay
  name: checkout-delay
spec:
  service: checkout
  description: Track the latency in Ordering API
  budgetingMethod: Timeslices
  objectives:
    - displayName: SLI to track latency
      target: 0.99
      timeSliceTarget: 0.9
      ratioMetrics:
        total:
          source: sumologic
          queryType: Logs
          query: |
            _index=_trace_spans | (endtimestamp - starttimestamp) / 1000000 as duration 
            | json field=tags "['target_xpath']" 
            | where tolowercase(service) = "the-coffee-bar-frontend"
              and tolowercase(operation) = tolowercase("click on \"Checkout\"") 
              and tolowercase(%"['target_xpath']") = "//*[@id=\"checkout\"]"
        good:
          source: sumologic
          queryType: Logs
          query: duration_ms < 400
createView: true
fields:
labels:
  tier: 0
alerts:
  burnRate:
    - shortWindow: '10m'
      shortLimit: 2
      longWindow: '1h'
      longLimit: 4
      notifications:
        - connectionType: 'Email'
          recipients:
            - 'agaurav@sumologic.com'
          triggerFor:
            - Warning
            - ResolvedWarning
    - shortWindow: '2h'
      shortLimit: 4
      longWindow: '24h'
      longLimit: 1
      notifications:
        - connectionType: 'Email'
          recipients:
            - 'agaurav@sumologic.com'
          triggerFor:
            - Warning
            - ResolvedWarning
